import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Belanosima } from 'next/font/google';
import { notFound } from 'next/navigation';
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const belanosima = Belanosima({
  subsets: ['latin'],
  weight: ['400', '700'], // adjust based on your usage
  display: 'swap'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
   
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#00281A] text-white`}>
          {children}
      </body>
    </html>
  );
}
